### ISSUE TITLE
Test case for pem that could cause leading zero modulus issue

### ISSUE THREAD

**Issue by henrjk** [dannycoates/pem-jwk#2]
Chrome's crypto implementation rejects jwk's when the modulus n has leading zeroes. 

[Chrome Issue 383998:	Reject JWK which use non-minimal octet representation for big integers](https://code.google.com/p/chromium/issues/detail?id=383998#c6) makes the case that this behaviour of Chrome is according to spec. 

I noticed this issue when I worked on implementing anvilresearch/connect-js to use webcrypto and found that a jwk in its test suite was rejected by Chrome 47.0.2526.

This project uses pem-jwk. I have written a test for pem-jwk to ensure that the PEM representing the problematic jwk would not cause this issue now.      

If there is interest to add this test I'd be happy to submit a PR for adding this test.

**Comment by henrjk** [comment]
Actually connect-js is not using pem-jwk but the server side which also supports generating keys does.

**Comment by dannycoates** [comment]
As far as I know, this module doesn't add any padding to the base64 encoded numbers. If you have an example jwk generated by this module that does, I'd love to see it.
